apiVersion: v1
kind: Service
metadata:
  name: globomantics-appsvc
spec:
  selector:
    app: globomantics-appsvc
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globomantics-appsvc
  labels:
    name: globomantics-appsvc
spec:
  selector:
    matchLabels:
      app: globomantics-appsvc
  replicas: 1
  template:
    metadata:
      labels:
        app: globomantics-appsvc
    spec:
      containers:
        - name: globomantics-appsvc
          image: <IMAGE_URI_FROM_ECR>
          imagePullPolicy: Always
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - containerPort: 5000
